# DartやFlutterのプロジェクトでは、pubspec.yamlファイルを使用してパッケージの依存関係を管理する
# パッケージを追加するには、dependenciesセクションにパッケージ名とバージョンを追記する
# 例えば、httpパッケージを追加する場合、pubspec.yamlファイルは次のようになる

# http: ^0.13.3はhttpパッケージのバージョン0.13.3以上を意味する
# ^記号は、メジャーバージョン内で最新のバージョンを使用することを示す

# パッケージを追加したら、ターミナルでflutter pub getコマンドを実行して、パッケージをダウンロードしてインストールする
# このコマンドは、pubspec.yamlファイルを読み取り、指定されたパッケージをダウンロードしてインストールする
# これにより、新たに追加したパッケージがプロジェクトで利用可能になります。

# なお、このコマンドを実行すると、pubspec.lockファイルが生成される
# pubspec.lockファイルは、プロジェクトにインストールされたパッケージのバージョン情報を保持する
# このファイルは、パッケージのバージョンを固定するために使用される
# このファイルを削除すると、flutter pub getコマンドを再度実行すると、pubspec.yamlファイルに記述されたバージョンのパッケージがインストールされる


#name: my_project
#description: A new Flutter project.
#
## ...
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  # 追加するパッケージ
#  http: ^0.13.3
#
#  # ...
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
## ...